Product As screen:

    Component1_22 As Component1:
        Height: =69

    MenuLeftNav_23 As MenuLeftNav:
        Height: =MenuLeftNav_23.MenuHeight
        MenuWidth: =If(showMenu, MenuLeftNav_23.SetMenuWidth,icoHamburger_1.Width)
        OnReset: =Set(showMenu, MenuLeftNav_23.ExpandMenu)
        Width: =MenuLeftNav_23.MenuWidth
        Y: =10
        ZIndex: =2

    Label7_5 As label:
        Align: =Align.Center
        Fill: =RGBA(209, 232, 178, 1)
        Height: =70
        Size: =21
        Text: ="Product"
        Width: =640
        Y: =69
        ZIndex: =3

    Product_form As form:
        DataSource: =Products
        Height: =915
        Width: =640
        Y: =137
        ZIndex: =4

        "'Default Unit_DataCard1' As typedDataCard.comboBoxEditCard":
            BorderStyle: =BorderStyle.Solid
            DataField: ="defaultuomid"
            Default: =ThisItem.'Default Unit'
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@Products],DataSourceInfo.DisplayName,"defaultuomid")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            Required: =false
            Update: =DataCardValue40.Selected
            Width: =640
            X: =0
            Y: =2
            ZIndex: =1

            DataCardKey50 As label:
                AutoHeight: =true
                Height: =48
                Size: =21
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue40 As combobox:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                DefaultSelectedItems: =Parent.Default
                DisplayFields: =["name"]
                DisplayMode: =Parent.DisplayMode
                Height: =70
                IsSearchable: =false
                Items: =Choices([@Products].defaultuomid)
                PaddingLeft: =If(Self.DisplayMode = DisplayMode.Edit, 5, 0)
                SearchFields: =["name"]
                SearchItems: =[]
                SelectMultiple: =false
                Size: =21
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey50.Y + DataCardKey50.Height + 5
                ZIndex: =2

            ErrorMessage49 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =24
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue40.Y + DataCardValue40.Height
                ZIndex: =3

            StarVisible49 As label:
                Align: =Align.Center
                Height: =DataCardKey50.Height
                Size: =21
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey50.Y
                ZIndex: =4

        "'Default Price List_DataCard1' As typedDataCard.comboBoxEditCard":
            BorderStyle: =BorderStyle.Solid
            DataField: ="pricelevelid"
            Default: =ThisItem.'Default Price List'
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@Products],DataSourceInfo.DisplayName,"pricelevelid")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            Required: =false
            Update: =DataCardValue41.Selected
            Width: =640
            X: =0
            Y: =3
            ZIndex: =1

            DataCardKey51 As label:
                AutoHeight: =true
                Height: =48
                Size: =21
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue41 As combobox:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                DefaultSelectedItems: =Parent.Default
                DisplayFields: =["name"]
                DisplayMode: =Parent.DisplayMode
                Height: =70
                Items: =Choices([@Products].pricelevelid)
                PaddingLeft: =If(Self.DisplayMode = DisplayMode.Edit, 5, 0)
                SearchFields: =["name"]
                SearchItems: =Search(Choices([@Products].pricelevelid),DataCardValue41.SearchText,"name")
                SelectMultiple: =false
                Size: =21
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey51.Y + DataCardKey51.Height + 5
                ZIndex: =2

            ErrorMessage50 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =24
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue41.Y + DataCardValue41.Height
                ZIndex: =3

            StarVisible50 As label:
                Align: =Align.Center
                Height: =DataCardKey51.Height
                Size: =21
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey51.Y
                ZIndex: =4

        "'Unit Group_DataCard1' As typedDataCard.comboBoxEditCard":
            BorderStyle: =BorderStyle.Solid
            DataField: ="defaultuomscheduleid"
            Default: =ThisItem.'Unit Group'
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@Products],DataSourceInfo.DisplayName,"defaultuomscheduleid")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            Required: =false
            Update: =DataCardValue42.Selected
            Width: =640
            X: =0
            Y: =4
            ZIndex: =1

            DataCardKey52 As label:
                AutoHeight: =true
                Height: =48
                Size: =21
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue42 As combobox:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                DefaultSelectedItems: =Parent.Default
                DisplayFields: =["name"]
                DisplayMode: =Parent.DisplayMode
                Height: =70
                Items: =Choices([@Products].defaultuomscheduleid)
                PaddingLeft: =If(Self.DisplayMode = DisplayMode.Edit, 5, 0)
                SearchFields: =["name"]
                SearchItems: =Search(Choices([@Products].defaultuomscheduleid),DataCardValue42.SearchText,"name")
                SelectMultiple: =false
                Size: =21
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey52.Y + DataCardKey52.Height + 5
                ZIndex: =2

            ErrorMessage51 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =24
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue42.Y + DataCardValue42.Height
                ZIndex: =3

            StarVisible51 As label:
                Align: =Align.Center
                Height: =DataCardKey52.Height
                Size: =21
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey52.Y
                ZIndex: =4

        Name_DataCard1 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="name"
            Default: =ThisItem.Name
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@Products],DataSourceInfo.DisplayName,"name")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@Products], DataSourceInfo.MaxLength, "name")
            Required: =true
            Update: =DataCardValue1.Text
            Width: =640
            X: =0
            Y: =0
            ZIndex: =5

            DataCardKey1 As label:
                AutoHeight: =true
                Height: =48
                Size: =21
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue1 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                Height: =70
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Size: =21
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey1.Y + DataCardKey1.Height + 5
                ZIndex: =2

            ErrorMessage47 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =24
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue1.Y + DataCardValue1.Height
                ZIndex: =3

            StarVisible47 As label:
                Align: =Align.Center
                Height: =DataCardKey1.Height
                Size: =21
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey1.Y
                ZIndex: =4

        "'Field Service Product Type_DataCard1' As typedDataCard.comboBoxOptionSetSingleEditCard":
            BorderStyle: =BorderStyle.Solid
            DataField: ="msdyn_fieldserviceproducttype"
            Default: =ThisItem.'Field Service Product Type'
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@Products],DataSourceInfo.DisplayName,"msdyn_fieldserviceproducttype")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            Required: =false
            Update: =DataCardValue39.Selected.Value
            Width: =640
            X: =0
            Y: =1
            ZIndex: =5

            DataCardKey49 As label:
                AutoHeight: =true
                Height: =48
                Size: =21
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue39 As combobox:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                DefaultSelectedItems: =[Parent.Default]
                DisplayFields: =["Value"]
                DisplayMode: =Parent.DisplayMode
                Height: =70
                IsSearchable: =false
                Items: =Choices('Field Service Product Type')
                PaddingLeft: =If(Self.DisplayMode = DisplayMode.Edit, 5, 0)
                SearchFields: =["Value"]
                SearchItems: =[]
                SelectMultiple: =false
                Size: =21
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey49.Y + DataCardKey49.Height + 5
                ZIndex: =2

            ErrorMessage48 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =24
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue39.Y + DataCardValue39.Height
                ZIndex: =3

            StarVisible48 As label:
                Align: =Align.Center
                Height: =DataCardKey49.Height
                Size: =21
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey49.Y
                ZIndex: =4

    Button18 As button:
        Height: =72
        OnSelect: =SubmitForm(Product_form);ResetForm(Product_form)
        Size: =24
        Text: ="Create Product"
        Width: =640
        Y: =1064
        ZIndex: =5

