product As screen:

    "Gallery11 As gallery.'BrowseLayout_Vertical_ThreeTextVariant_ver4.0'":
        Height: =999
        Items: =Products
        Layout: =Layout.Vertical
        TemplatePadding: =0
        TemplateSize: =250
        Y: =135
        ZIndex: =1

        Title11 As label:
            Height: =36
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Name
            VerticalAlign: =VerticalAlign.Top
            Width: =402
            X: =238
            ZIndex: =1

        Subtitle7 As label:
            Height: =35
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.'Product ID'
            VerticalAlign: =VerticalAlign.Top
            Width: =402
            X: =238
            Y: =101
            ZIndex: =2

        Body4 As label:
            Height: =54
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.'Product Type'
            VerticalAlign: =VerticalAlign.Top
            Width: =402
            X: =238
            Y: =183
            ZIndex: =3

        NextArrow8 As icon.ChevronRight:
            AccessibleLabel: =Self.Tooltip
            Height: =60
            Icon: =Icon.ChevronRight
            OnSelect: =Select(Parent)
            PaddingBottom: =10
            PaddingLeft: =10
            PaddingRight: =10
            PaddingTop: =10
            TabIndex: =0
            Tooltip: ="View item details"
            Width: =60
            X: =Parent.TemplateWidth - Self.Width - 5
            Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
            ZIndex: =4

        Separator21 As rectangle:
            Height: =1
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =5

        Label22 As label:
            FontWeight: =FontWeight.Bold
            Height: =36
            OnSelect: =Select(Parent)
            Size: =21
            Text: |-
                ="Name:"
            Width: =560
            ZIndex: =6

        Label22_1 As label:
            FontWeight: =FontWeight.Bold
            Height: =41
            OnSelect: =Select(Parent)
            Size: =21
            Text: |-
                ="Product ID:"
            Width: =238
            Y: =95
            ZIndex: =7

        Label22_2 As label:
            FontWeight: =FontWeight.Bold
            Height: =41
            OnSelect: =Select(Parent)
            Size: =21
            Text: |-
                ="Product Type:"
            Width: =238
            Y: =183
            ZIndex: =8

    Component1_16 As Component1:
        Height: =70
        ZIndex: =2

    Label7_3 As label:
        Align: =Align.Center
        Fill: =RGBA(209, 232, 178, 1)
        Height: =70
        Size: =21
        Text: ="Products"
        Width: =640
        Y: =65
        ZIndex: =3

    MenuLeftNav_9 As MenuLeftNav:
        ExpandMenu: =true
        Height: =MenuLeftNav_9.MenuHeight
        Visible: =true
        Width: =MenuLeftNav_9.MenuWidth
        ZIndex: =5

