Product As screen:

    Component1_22 As Component1:
        Height: =69

    MenuLeftNav_23 As MenuLeftNav:
        Height: =MenuLeftNav_23.MenuHeight
        MenuWidth: =If(showMenu, MenuLeftNav_23.SetMenuWidth,icoHamburger_1.Width)
        OnReset: =Set(showMenu, MenuLeftNav_23.ExpandMenu)
        Width: =MenuLeftNav_23.MenuWidth
        Y: =10
        ZIndex: =2

    Label7_5 As label:
        Align: =Align.Center
        Fill: =RGBA(209, 232, 178, 1)
        Height: =70
        Size: =21
        Text: ="Product"
        Width: =640
        Y: =69
        ZIndex: =3

